# Generated by Django 3.1.1 on 2021-03-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiji', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishuser',
            new_name='myuser',
        ),
    ]
