# Generated by Django 3.1.1 on 2021-03-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiji', '0003_auto_20210318_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishactivities',
            name='actiimage',
        ),
        migrations.RemoveField(
            model_name='wishevents',
            name='eventimage',
        ),
        migrations.RemoveField(
            model_name='wishfood',
            name='foodimage',
        ),
        migrations.RemoveField(
            model_name='wishhotel',
            name='hotelimage',
        ),
    ]
