# Generated by Django 3.1.1 on 2021-03-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiji', '0005_auto_20210318_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishflight',
            new_name='Wishflights',
        ),
        migrations.RenameModel(
            old_name='Wishhotel',
            new_name='Wishhotels',
        ),
    ]
